### ISSUE TITLE
Maxout units and subtractive normalization

### ISSUE THREAD

**Issue by markusjudge** [potterhsu/SVHNClassifier#7]
Hello @potterhsu,

first I want to thank you for your implementation, it is doing great for me so far.

As I was reading the original paper by Goodfellow et al. I noticed that they mention the use of maxout units for the first hidden layer and relu elsewhere. Furthermore they use subtractive normalization. In your implementation, however, you use batch_normalization and relu activation functions on all layers. So, did I miss something or what were your reasons for those modifications? Thanks.

**Comment by potterhsu** [comment]
It was just for convenience to apply the off-the-shelf functions which were officially supported.
You may try maxout for better performance.

**Comment by markusjudge** [comment]
ok, thank you, I may try it.
