### ISSUE TITLE
read and convert svhn dataset

### ISSUE THREAD

**Issue by markusjudge** [potterhsu/SVHNClassifier#9]
Hello potterhsu,

I noticed the following in the `convert_to_tfrecords.py` file:

`for idx, label_of_digit in enumerate(label_of_digits):`
`digits[idx] = int(label_of_digit if label_of_digit != 10 else 0)  # label 10 is essentially digit zero`

is this really correct? The digit zero is actually a digit while 10 is a no digit at all.

**Comment by potterhsu** [comment]
As [SVHN Dataset](http://ufldl.stanford.edu/housenumbers/) mentioned:
> 10 classes, 1 for each digit. Digit '1' has label 1, '9' has label 9 and '0' has label 10.

To be clarified, what the for-loop do is mapping from
```
Original SVHN Dataset Label
    one to nine: 1 ~ 9
    zero: 10
```
to
```
Our Label
    zero: 0
    one to nine: 1 ~ 9
```
